### ISSUE TITLE
Zygisk/Magisk Module

### ISSUE THREAD

**Issue by 7heMech** [pyoncord/Bunny#101]
Would it be possible to implement a module for Zygisk instead of the Xposed one in the future?

**Comment by PalmDevs** [comment]
Why?

**Comment by 7heMech** [comment]
@PalmDevs because my phone has root with Magisk and the new Magisk uses Zygisk which should have support for LSposed, but LSposed doesn't work a part of the phones, and doesn't seem like it will be fixed.
