### ISSUE TITLE
bug: Constant Crashing [iOS]

### ISSUE THREAD

**Issue by sleepdeprivediris** [pyoncord/Bunny#103]
**Describe the bug**
“ Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.”

**To Reproduce**
1. Launch the app
2. See error

**Expected behavior**
The app will load but not completely before crashing, retrying to render sometimes work but not every time.

**Screenshots**
![IMG_0817](https://github.com/user-attachments/assets/cc672c4f-c2d3-407c-8583-b9e560b5eab7)
![IMG_0818](https://github.com/user-attachments/assets/f873cf22-5471-44de-89e5-c930f0202c5f)

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone15]
 - OS: [e.g. iOS 18.1]
 - Discord Version [e.g. 64408]
 - Bunny Version [e.g a0d467a-main]

**Checklists**
- [✅ ] I understand that this is a bug report and not a place to request new features or plugins
- [✅ ] I understand that this is no place to report bugs produced by a plugin
- [❌ ] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by PalmDevs** [comment]
From the last point in the checklist not being checked, I assume you have a plugin that doesn't work on iOS. Try turning on Safe Mode if you can and check.
