### ISSUE TITLE
bug: Bunny won't work under Android 15

### ISSUE THREAD

**Issue by Snupai** [pyoncord/Bunny#104]
**Describe the bug**
Discord with Bunny patch installed using Bunny Manager won't start at all under Android 15. Stuck showing discord logo before eventually crashing. 

**To Reproduce**
1. Be on Android 15
2. Install Bunny Manager
3. Install Bunny
4. Start Bunny

**Expected behavior**
Bunny starts and shows dms or last server. 

**Screenshots**
![Screenshot_20241106-171352](https://github.com/user-attachments/assets/444f9062-a263-45d9-9467-5558b76cc3d2)

**Device Information (please complete the following information):**
 - Device: Nothing Phone (2)
 - OS: Android 15
 - Discord Version 252014
 - Bunny Version 66026b4-main

**Checklists**
- [x] I understand that this is a bug report and not a place to request new features or plugins
- [x] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by amsryq** [comment]
![image](https://github.com/user-attachments/assets/86faa165-b32b-44a3-96bd-d9461a7f8e4f)
