### ISSUE TITLE
[bug]: Bunny breaks on 256.02 alpha (latest)

### ISSUE THREAD

**Issue by mudrhiod** [pyoncord/Bunny#108]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

1. Install latest alpha with Bunny manager (it should be installing 256.02 or higher)
2. Open installed app
3. Get an alert saying "failed to load bunny"

### Expected behavior

App should open and not show an error message saying bunny failed to load. Bunny's section should also show in the settings page with all add-ons working 

### Actual behavior

App opens and displays failed to load bunny alert

### Screenshots/Screen recordings

![Screenshot_2024-11-13-08-43-46-28](https://github.com/user-attachments/assets/7dd0bd3c-1c74-46f9-9bd4-987583d20e37)

### What platform did you produce this issue on?

Android

### Discord version

256.02 (256202)

### Version

6f52993-main

### Loader version

BunnyXposed (0.2.4)

### Device

OnePlus 11

### OS version

Android 14

**Comment by Mario-119** [comment]
Can confirm the same issue on my device (Moto Edge+ 2023 running Android 14), tried a fresh install as well to no avail.
