### ISSUE TITLE
[bug]: Notifications not showing

### ISSUE THREAD

**Issue by Fudge1q** [pyoncord/Bunny#109]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

Get a dm or ping
No badge on the app or notification
However i get an in app botification

### Expected behavior

Should be giving me a banner notification for dms and unmuted servers
And a badge for muted servers snd dms

### Actual behavior

No notifications at all except inside the app(i can see pings and get the inbuilt discord notifs)

### What platform did you produce this issue on?

iOS

### Discord version

254.0

### Version

Bunny - e80ab84-main

### Loader version

0.4.0

### Device

Iphone 11 and 16 base model

### OS version

18.1.1

**Comment by castdrian** [comment]
sideloaded applications require the push notification entitlement to receive push notifications. this is not an issue with the mod.

**Comment by Fudge1q** [comment]
> sideloaded applications require the push notification entitlement to receive push notifications. this is not an issue with the mod.

What do you mean by push notification entitlement. Do i just delete discord?

**Comment by castdrian** [comment]
> What do you mean by push notification entitlement

https://developer.apple.com/documentation/bundleresources/entitlements

**Comment by Fudge1q** [comment]
> > What do you mean by push notification entitlement
> 
> https://developer.apple.com/documentation/bundleresources/entitlements

So it just wont have notifications ever?

**Comment by Fudge1q** [comment]
@castdrian is there any way to get notifications
