### ISSUE TITLE
Many issues from java file errors to performance issues

### ISSUE THREAD

**Issue by daedaevibin** [pyoncord/Bunny#110]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

Unsure. For what I know, it is not caused by a plugin and happened after the latest update.

### Expected behavior

Not causing my phone to overheat, not failing to load the js file properly, not failing to load chats and servers entirely, and not failing to load to the point it temporarily reverts to a standard discord application.

### Actual behavior

Failing to load, overheating, reverting to standard discord, etc.

### What platform did you produce this issue on?

Android

### Discord version

255.14

### Version

e80ab84-main

### Loader version

Bunny Xposed (0.2.5)

### Device

Google Pixel 6a

### OS version

Android 14 (Bliss ROMs 17.1)

### Additional information

I see the issue might be the Xposed loader. I've never used the Xposed module let alone nothing is installed for it. Odd that it's defaulted to that without reason or the ability to do so.

**Comment by castdrian** [comment]
> I've never used the Xposed module let alone nothing is installed for it.

That is not exactly correct, you are indeed using the xposed module as loader, it just isn’t hooking into the app via lsposed, it’s instead injected into the app binaries using lspatch and doing its stuff that way 

as for the issues, you mentioned there’s a multitude of possibilities but the main best guess here is 

a) Android & React Native are known to cause performance issues in conjunction, also discord doesn’t write particularly optimized react

b) the bundle loading issues most likely stem from your OS being customized, LSPosed and LSPatch are abandoned and despite forks being maintained they may or may not cause unexpected behavior when used on newer OS versions especially when using customized distros

**Comment by daedaevibin** [comment]
> > I've never used the Xposed module let alone nothing is installed for it.
> 
> That is not exactly correct, you are indeed using the xposed module as loader, it just isn’t hooking into the app via lsposed, it’s instead injected into the app binaries using lspatch and doing its stuff that way
> 
> as for the issues, you mentioned there’s a multitude of possibilities but the main best guess here is
> 
> a) Android & React Native are known to cause performance issues in conjunction, also discord doesn’t write particularly optimized react
> 
> b) the bundle loading issues most likely stem from your OS being customized, LSPosed and LSPatch are abandoned and despite forks being maintained they may or may not cause unexpected behavior when used on newer OS versions especially when using customized distros

I do not have lsposed, lspoatch, xposed, or the actual module for bunny installed. I never had, and even installed bunny via the manager before rooting. it forcibly changed to the module, it does not have root access, and is completely blocked from magisk. I should not be using that as the loader right?

**Comment by amsryq** [comment]
> I do not have lsposed, lspatch, xposed, or the actual module for bunny installed.
BunnyManager does that for you. Xposed modules do not require root when used with root-free Xposed frameworks like LSPatch. In this case, LSPatch will embed the module into the apk for you *through* the manager.

Closing as this issue is not clear enough and most likely hardware specific issue
