### ISSUE TITLE
Will translation plug-ins be added?

### ISSUE THREAD

**Issue by ysnx64523** [pyoncord/Bunny#112]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [ ] The title of this issue accurately describes the feature request.

### Feature description

Can you upload a translation message plugin?
Automatically translate your language into the target language when sending a message.
Translate the message on the channel from a certain language to a specified language.

### Why do you want this feature?

I am a user of other languages, and I can't speak English.
Some people may not know English either.

**Comment by amsryq** [comment]
Sorry, this repository is not for plugin requests
