### ISSUE TITLE
[bug]: "Failed to fetch JS bundle, Bunny may not load"

### ISSUE THREAD

**Issue by Obnomus** [pyoncord/Bunny#113]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

Simply open the app and it'll show "Failed to fetch JS bundle, Bunny may not load"

### Expected behavior

App should open without throwing any error

### Actual behavior

thorws an error - "Failed to fetch JS bundle, Bunny may not load"

### Screenshots/Screen recordings

![bunny](https://github.com/user-attachments/assets/d289fced-a652-48bc-b59a-faaa5b8a8f39)

### What platform did you produce this issue on?

Android

### Discord version

Stable 255.14

### Version

e80ab84-main

### Loader version

Bunny 0.2.5

### Device

OnePlus 7 Pro

### OS version

Android 15 custom rom

**Comment by castdrian** [comment]
Try a different network or dns server, your network failed to fetch the mod bundle

**Comment by AsterionXeity** [comment]
> Try a different network or dns server, your network failed to fetch the mod bundle

What server cause I have the same happen

**Comment by castdrian** [comment]
I'd try CF 1.1.1.1 or Google 8.8.8.8

**Comment by Obnomus** [comment]
Tbh I don't know what the issue is cuz on my other device with same network and all everything works fine

**Comment by castdrian** [comment]
Quad9 is also fairly reputable, 9.9.9.9

**Comment by AsterionXeity** [comment]
> Quad9 is also fairly reputable, 9.9.9.9

My router already uses this
