### ISSUE TITLE
Plugins Failing

### ISSUE THREAD

**Issue by rodney528** [pyoncord/Bunny#116]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [ ] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

Updating Pyoncord.

### Expected behavior

All plugins active and working.

### Actual behavior

Some plugins are unable to be turned on after updating.

### What platform did you produce this issue on?

Android

### Discord version

257.15

### Version

e80ab84-main

### Loader version

Loader - PyoncordXposed (undefined)

### Device

Galaxy Note 10+

### OS version

Android 12

### Debug information

**Bunny Debug Info**
> Bunny: e80ab84-main (PyoncordXposed undefined)
> Discord: 257.15 (257015)
> React: 18.3.1 (RN 0.74.5-discord-11)
> Hermes: for RN 0.74.5-discord-11 (bcv96)
> System: Android 12 (SDK 31)
> Device: SM-N975U1 (d2q)

### Additional information

I've tried turning on the plugins and reinstalling but it doesn't seem to work.

**Comment by rodney528** [comment]
I switched loaders but still. Some plugins did come back, not all of them tho.

**Comment by Rico040** [comment]
Read 5th checkmark.

**Comment by rodney528** [comment]
bruh wtf

**Comment by rodney528** [comment]
I didn't read it because they all had the red *, as in required.

**Comment by theacrat** [comment]
Are they all unproxied? I've noticed that all of my unproxied plugins are unable to be turned on.

Edit: mine were all plugins by Nexpid and it was resolved changing the link I used as they sunset the domain I was using. May be different issue if yours are other plugins.

**Comment by rodney528** [comment]
> Are they all unproxied? I've noticed that all of my unproxied plugins are unable to be turned on.
> 
> Edit: mine were all plugins by Nexpid and it was resolved changing the link I used as they sunset the domain I was using. May be different issue if yours are other plugins.

Possibly, I'll have to check.

**Comment by rodney528** [comment]
> Are they all unproxied? I've noticed that all of my unproxied plugins are unable to be turned on.
> 
> Edit: mine were all plugins by Nexpid and it was resolved changing the link I used as they sunset the domain I was using. May be different issue if yours are other plugins.

How do I check for unproxied plugins?

**Comment by MrIceblock** [comment]
Can confirm a bunch of addons like "Bluetooth Audio Fix" and "BetterSearch" are broken in the latest update.

**Comment by castdrian** [comment]
add-ons are the burden of their respective developers, opening GitHub issues on the mod repo will not have any effect on that particular situation.
