### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by daedaevibin** [pyoncord/Bunny#117]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

Open the manager, try to update the app, be told it's a conflicting package.

### Expected behavior

Open the manager, try to update the app, update easily.

### Actual behavior

Open manager, try to update, wait on everything to download and patch, it's a conflicting package.

### What platform did you produce this issue on?

Android

### Discord version

255.14

### Version

e80ab84-main

### Loader version

Bunny Xposed (0.2.5) (THIS IS NOT INSTALLED THOUGH)

### Device

Google Pixel 6a

### OS version

Android 15 (Bliss ROMs 18.0)

### Additional information

The only valid option would be to uninstall and reinstall but I seriously should not because of plugins I need, and a certain plugin being under maintenance still.

**Comment by castdrian** [comment]
this happened because your OS cleared wherever the app stores the keystore it used to sign the app, pretty sure dev mode options lets you export and import the keystore so just keep a local copy of it saved somewhere and import it if need be

**Comment by senina4** [comment]
> this happened because your OS cleared wherever the app stores the keystore it used to sign the app, pretty sure dev mode options lets you export and import the keystore so just keep a local copy of it saved somewhere and import it if need be

I don't see it in dev mode opinion
