### ISSUE TITLE
Unable to roll back Bunny version

### ISSUE THREAD

**Issue by DrWhoFan13** [pyoncord/Bunny#13]
Hello there, I've heard good things about Bunny and have recently installed it. However, because I installed it on the most recent version of Discord, it freezes on startup and a look at the README revealed the incompatibility issue.

So I have to ask: How do I roll back the version of Discord to install Bunny?

**Comment by amsryq** [comment]
Not sure why this is closed, but it entirely depends on the platform. You usually can't downgrade apps on Android but (I think) it's feasible on iOS through sideloading. Downgrading can cause the app to be unstable anyway, so I'd recommend a fresh install

**Comment by DrWhoFan13** [comment]
It was closed because I had difficulty figuring out the version number needed for compatibility when I made it. I since fixed it.
