### ISSUE TITLE
Bunny doesn't work on 223.15 stable

### ISSUE THREAD

**Issue by ghost** [pyoncord/Bunny#15]
When opening discord with the module enabled, it stucks at loading screen. Trying to force stop the app and clear storage wont fix it.

**Comment by amsryq** [comment]
![Screenshot_20240402-141221_Discord](https://github.com/pyoncord/Pyoncord/assets/82711525/dd0bada3-fd7a-458a-a288-f59df0cb6a60)

Though, latest stable still shows up as 222.13 (222013) for me
