### ISSUE TITLE
downloads Vendetta Module forever

### ISSUE THREAD

**Issue by Xodabeef** [pyoncord/Bunny#16]
I followed the instructions for Vendetta Manager, but after pressing Reinstall the installer is stuck on "downloading Vendetta Module". Maybe it's a file path issue? I placed the file in the downloads folder,  but since I'm on a user account different to the Admin/First account maybe that changes the file path? I don't have much to loose as normal Vendetta is just plain broken, but I'd appreciate help with this issue.

**Comment by amsryq** [comment]
> I'm on a user account different to the Admin/First account maybe that changes the file path?

I'm not sure but that's likely. You can use your preferred file manager to obtain the full path to the module you downloaded to confirm

Also, make sure to give the manager "All files access"  permission, it's needed for it to read the Download folder

**Comment by Xodabeef** [comment]
> I'm not sure but that's likely. You can use your preferred file manager to obtain the full path to the module you downloaded to confirm

It was the cause indeed. I did give VM the full file access permission. The fix was simply using `storage/emulated/10/[...]` instead of `storage/emulated/0/[...]`, as 0 does not stay consistent with user accounts while 10 does. This is probably because different users get different seperate file systems and 0 is just the admin or so, while 10 contains system data which is shared between accounts. So, i suggest maybe adding a section to the readme so future users who may run into the same problem know about the fix. (My final filepath was `storage/emulated/10/Android/experimente/app-release.apk`, experimente being a folder i added myself.)
