### ISSUE TITLE
new menu causes crash

### ISSUE THREAD

**Issue by mollyvita** [pyoncord/Bunny#2]
### steps to reproduce:
1. press settings icon near plugin/theme
2. try to exit it with gesture/back button/etc
3. crash! (just exits the app)

### notes:
if you try to do the same with new attachment menu, it kills swiping back to channel list (you can do it only with gesture/back button)

**Comment by mollyvita** [comment]
another note: attachment menu thing happens on stock vd too

**Comment by amsryq** [comment]
Mhm yeah, a quirk of the new component.. it demands the component to stay on render until the menu fully closes. When you press back, it exits the page, thus _unrender_ the component before the menu and _boom_

**Comment by amsryq** [comment]
I'm pretty sure that's unintended, since there's no "back" on iOS (where the component is built most likely)... I'll try to get around this or just resort back to the action sheet

**Comment by PalmDevs** [comment]
This happens inside the Design systems > Context menu page under Staff Settings section too.

**Comment by amsryq** [comment]
Implemented a fix in 34bc869a07004c6b120b2fb8a3e8a03c984cb68d
