### ISSUE TITLE
Feature request: Font override support

### ISSUE THREAD

**Issue by tmprnc** [pyoncord/Bunny#21]
Hello,
I switched over from Revenge upon learning that it was sunset. I have been using a [custom modification](https://gist.github.com/tmprnc/5af6e755d1b60262744f5a779689b41f) of the Catppuccin theme which changes two things:
1. Adds in Rosiecord icons from other themes
2. Overrides all fonts to be Atkinson Hyperlegible, a dyslexia-friendly font that eases readability.

The first part of this mod works just fine still. The second, not so much.
It seems Bunny doesn't support font overrides the way Vendetta and Revenge did. May this feature be brought back?

Thank you

**Comment by mollyvita** [comment]
vendetta didn't support fonts (it wasn't done yet when vendetta eol'd)

**Comment by tmprnc** [comment]
I stand corrected. I might have misremembered the timeline of when I added fonts to the theme. It did definitely work under Revenge, however.
