### ISSUE TITLE
Vendetta doesn't start

### ISSUE THREAD

**Issue by zerobun** [pyoncord/Bunny#26]
When I first installed it using the module, it was working fine. After the recent alpha update, it kept giving this same error. I tried using beta and stable versions too. Same result

![Screenshot_20240429-183608](https://github.com/pyoncord/Bunny/assets/127630316/2ad3a571-7e2a-4f21-9d05-d77ba8ac1ded)

**Comment by amsyarasyiq** [comment]
Try using BunnyManager
