### ISSUE TITLE
Can’t get the tweak to work

### ISSUE THREAD

**Issue by Sinclair-Speccy** [pyoncord/Bunny#3]
It’s sheer impossible for me to get this to even work as the instructions say to get VendettaTweak from the prebuilt .deb files from GitHub Actions for Vendetta, but VendettaTweak doesn’t even install in the first place to be able to use this.

Maybe I’m doing something wrong but it says to get the deb file for VendettaTweak from the GitHub actions, which I do and it gives me a zip to unpack and then a deb file named Vendetta to install within Sileo. Trying to install it gives me an error about a pathname not being absolute

![13777972-FF80-49F3-9D5F-FF7A58791A26](https://github.com/pyoncord/Bunny/assets/73531055/0daa613b-0ddf-4333-92b4-a61426f87ce6)

**Comment by Sinclair-Speccy** [comment]
It says that Vendetta is already installed but it’s not, as the file disappears from my downloads

**Comment by Sinclair-Speccy** [comment]
Trying to install via sideloadly does not work either as I get this error. Either something is seriously wrong for me or something else as I tried on both a jailbroken device and non-jailbroken device:

![Capture](https://github.com/pyoncord/Bunny/assets/73531055/dcbbc477-eb7e-4257-b15a-01cedc70883a)

**Comment by amsryq** [comment]
This is unfortunately outside of my expertise, I don't have any experience using tweaks at all. I can only make a guess that this is related with rootless/rootful tweak there, since I haven't heard any issue with the tweak itself (ensure you use the right one)

As for the error from Sideloadly, assuming that you got the IPA from Vendetta IPAs thread, no that's not your fault, it's just an issue from the decrypted raw IPA. I'm not sure if you can circumvent that

**Comment by Sinclair-Speccy** [comment]
I tried both rootful and rootless but they both seem to give errors. The rootless one is the one that prevents being installed by Sileo by giving me actual errors so I assume my device needs the rootful version the one, which is in the screenshot. It acts like it installed but it does not and the deb file magically disappears nor does Sileo let me uninstall it.

For Sideloadly I got that from the readme from the host listed

**Comment by Mukul1127** [comment]
I made a unofficial tweak, maybe try that?

https://github.com/Mukul1127/BunnyUnofficialTweak

**Comment by PeterKW** [comment]
Did you get this working?

**Comment by Sinclair-Speccy** [comment]
I ended up giving up with getting it to work

**Comment by amsryq** [comment]
Can you try BunnyTweak? Refer to the readme.
Closing issue since it's irrelevant to the reoo (loader issue)
