### ISSUE TITLE
Why in the world I got banned I literally did nothing 

### ISSUE THREAD

**Issue by ghost** [pyoncord/Bunny#30]

**Comment by kasskasskasskasskass** [comment]
homophobic racist learns that consequences exist

**Comment by Vyntralised** [comment]
lmao

**Comment by amsryq** [comment]
![Screenshot_2024-05-04-17-26-38-327_com discord-edit](https://github.com/pyoncord/Bunny/assets/82711525/0bae8051-9dfa-4664-b250-38f003cad767)

**Comment by Zoomer1234** [comment]
the boy who cried wolf
