### ISSUE TITLE
question: Donation link?

### ISSUE THREAD

**Issue by candroid-man** [pyoncord/Bunny#32]
I would like to contribute to Bunny however I am far from a programmer. Is there anywhere I can donate? This is the only Android client left that I can tell, and I don't want this to go away!

**Comment by amsryq** [comment]
There's currently no way to donate the project or to me, for now

**Comment by Void48** [comment]
@amsyarasyiq just wanted to say that Bunny is great and thank you for forking Vendetta and keeping it alive ❤️
