### ISSUE TITLE
differences between rooted and rootless version for android? 

### ISSUE THREAD

**Issue by dxcvvxd** [pyoncord/Bunny#33]
i would like to install the rooted one but i dont really want to use x/lsposed, is there any difference between it and the rootless variant?

**Comment by Rico040** [comment]
rootless doesn't require root :trollface: 
and you have to update it manually through manager
passkeys doesn't work on it
and that it.

**Comment by Rico040** [comment]
rootless doesn't require root :trollface: 
and you have to update it manually through manager
passkeys doesn't work on it
and that it.

**Comment by dxcvvxd** [comment]
oh thanks!
this is really good to know and i wish it was briefly described in the readme...
