### ISSUE TITLE
Reaction Page Bug

### ISSUE THREAD

**Issue by OnyxJet** [pyoncord/Bunny#34]
When reacting to a message the emoji list gets cut off on the side. This prevents many emojis from being used as reactions since they are cut off by the side of the screen. 

The example here in on the right side.

![Screenshot_2024-05-04-23-13-18-89_ae4b61cddc56e7894f225aea7d9147d6](https://github.com/pyoncord/Bunny/assets/164056953/7b6288f7-c513-4df7-926f-9e7b02e9d6eb)

**Comment by amsryq** [comment]
Have you confirmed that this does not happen on the vanilla (unpatched) Discord?

**Comment by o800** [comment]
I checked and it happens on vanilla discord

**Comment by amsryq** [comment]
closing this issueーnot related to Bunny
