### ISSUE TITLE
[Minor Feature Request] Add QR code for easier BunnyManager download

### ISSUE THREAD

**Issue by inkstray** [pyoncord/Bunny#35]
# Why?
- It would allow for more quick sharing/downloading of the app.
# Ok but why
- I find it very convenient. It's not THAT important but its a missed oppertunity, I usually look for apps on PC and then id have to look for it again on my phone (heres where the QR comes in handy)

**Comment by Rairof** [comment]
1. Bunny is not available on PC.
2. Regular download links work just fine.

**Comment by inkstray** [comment]
fair enough
atleast i tried

**Comment by inkstray** [comment]
> 1. Bunny is not available on PC.
> 2. Regular download links work just fine.

also keep in mind im well aware that its not on PC
but i looked up the app on PC and with a simple scan i can just install directly to my phone

**Comment by Rico040** [comment]
![изображение](https://github.com/pyoncord/Bunny/assets/93081680/dd7829e8-80f3-4aca-a23d-68b41f6c7c63)
now you happy?

**Comment by inkstray** [comment]
yes, thank you :3
