### ISSUE TITLE
Manager stuck infinitely loading

### ISSUE THREAD

**Issue by Matthewkyos** [pyoncord/Bunny#36]
![Screenshot_20240508_063038_Bunny Manager](https://github.com/pyoncord/Bunny/assets/84089845/b369f29f-f693-4ae6-a955-91b38845520a)

**Comment by Rico040** [comment]
try changing mirror on advanced settings and/or turning off vpn

**Comment by Matthewkyos** [comment]
Changing mirror worked. Also the link to the discord is expired
![Uploading Screenshot_20240508_064305.png…]()

**Comment by Rico040** [comment]
which link?

**Comment by Matthewkyos** [comment]
The one in the manager itself
![Screenshot_20240508_064840_Bunny Manager](https://github.com/pyoncord/Bunny/assets/84089845/9aab030c-a121-489e-81ee-8e6726240cfa)

**Comment by Rico040** [comment]
pyoncord/BunnyManager#4

**Comment by Matthewkyos** [comment]
Im able to run the latest stable 227.12 instead of 223 whatever from the revenge fork of vendetta so that's nice everything else is working fine. Can close this thread if you want
