### ISSUE TITLE
My account was hacked 

### ISSUE THREAD

**Issue by ViVi-Vibes** [pyoncord/Bunny#39]
Dear [Pyoncord discord server owner],

I sincerely apologize for the recent disturbance caused by the hacker who spammed links. My account was compromised, and I take full responsibility for any inconvenience caused. I assure you, steps have been taken to secure my account to prevent any future breaches. I kindly request your understanding and would be grateful for the opportunity to be unbanned. 

Thank you for your attention to this matter.

Best regards,
[vaibhav1579]

**Comment by amsryq** [comment]
whitelisted your account
