### ISSUE TITLE
Manager is not installing the apk

### ISSUE THREAD

**Issue by Freenoob7878** [pyoncord/Bunny#43]
So I gave manager `install app from unknown source` permission but it's still showing me failed to install the apk. 

Here's the log: 
`05-18-2024 8:39:10pm [I] Done. Output APK: /storage/emulated/0/Android/data/io.github.pyoncord.manager/cache/229020/patched/lspatched/config.en-229020-407-lspatched.apk
05-18-2024 8:39:10pm [I] Installing apks
05-18-2024 8:39:28pm [E] 
05-18-2024 8:39:28pm [E] INSTALL_FAILED_INTERNAL_ERROR: Permission Denied`

**Comment by Rico040** [comment]
Relevent to https://github.com/vendetta-mod/VendettaManager/issues/73
Also include device info

**Comment by Freenoob7878** [comment]
Alright disabling MIUI optimization worked while installing the app. 

Thanks.
