### ISSUE TITLE
[Feature Request] Plugin to lock individual channels/Servers 

### ISSUE THREAD

**Issue by Mathew20kdroid** [pyoncord/Bunny#44]
Please add a plugin to lock individual channels/Servers.
It could be with a biometric verification (fingerprint).

**Comment by amsryq** [comment]
This is still not within Bunny's scope AND not a place to request plugins

**Comment by Mathew20kdroid** [comment]
😅 Can you please link me to the plugin repository....
Searched it but couldn't find it😓
