### ISSUE TITLE
Where I download specific version of Pyoncord?

### ISSUE THREAD

**Issue by Neme-sys-IO** [pyoncord/Bunny#45]
Like I want 223.5 version apk.

**Comment by Rico040** [comment]
Download Bunny Manager and unlock dev menu (on about menu tap 10 times manager's version) then go to dev menu and type "223205" on discord version field

**Comment by ErdbeerbaerLP** [comment]
1. Open bunny manager settings
2. Go to about
3. Tap the version number a few times
4. Go back
5. Open developer options
6. Set discord version to `223205` for 223.05.  If you intend to use the old ui, try `215024` (215.24 stable) instead
