### ISSUE TITLE
Audio in voice call is not being detected

### ISSUE THREAD

**Issue by rinnarii** [pyoncord/Bunny#47]
It works on vanilla Discord and Vendetta but not on Bunny

**Comment by TW527E** [comment]
In the official Bunny Discord Server has FAQ to explain.
https://discord.com/channels/1196075698301968455/1225842744291758111/1239472831864111158
![Screenshot_20240531_063820.jpg](https://github.com/pyoncord/Bunny/assets/37478187/622bbbb1-7bbc-41bc-aaa2-9ae0310b372e)
