### ISSUE TITLE
bug: The Mobile voice overlay text is invisible

### ISSUE THREAD

**Issue by ViVi-Vibes** [pyoncord/Bunny#48]
•**Steps to reproduce**:-
1. Join any VC
2. Scroll up from the call buttons and go to voice settings 
3. In voice settings enable Mobile Voice overlay.

•**Expected behaviour**
When the overlay is clicked there should be options for:-
• open discord
• copy the vc link 
• move the channel

•**Behaviour** 
The options are present and can still be clicked but the text is invisible.
![IMG_20240601_063344](https://github.com/pyoncord/Bunny/assets/134914549/0fc69cdb-533f-4b3b-a1bd-f0693375c782)

Also thanks for unbanning my account❤️.

**Comment by ViVi-Vibes** [comment]
Also I tried this in safe mode just to make sure it's not caused due to any of my plugins but it's the same in safe mode too, which means it's the pyoncord/bunny issue.

**Environment**
Device: Realme Nazro 20 A
OS: Realme UI 2.0 on Android 11
Installation type: Rooted via kitsune mask installed via Lsposed
Lsposed version: 1.9.2(latest)
Bunny version: e9d80c7-main
Discord version: 231.13 (231013)

**Bunny Debug Info**
> Bunny: e9d80c7-main (BunnyXposed 0.2.1)
> Discord: 231.13 (231013)
> React: 18.2.0 (RN 0.72.3-discord-35)
> Hermes: for RN 0.72.3-discord-35 (bcv94)
> System: Android 11 (SDK 30)
> Device: RMX2050 (RMX2050)

**Comment by TW527E** [comment]
In my case, unlike yours, my situation is very normal, even when not in Safe Mode.

My environment:
Phone: Samsung Galaxy S23+
OS: One UI 6.1 with Android 14
What Bunny: Non-root - BunnyManager
Bunny Ver.: e9d80c7-main
Discord Ver.: 231.13 (231013)
![Screenshot_20240601_101152](https://github.com/pyoncord/Bunny/assets/37478187/f148ccc1-a2c8-4bd7-b4cd-683333adc697)

There is not only one version of Bunny. If you can provide information like mine, I believe the maintenance team will be able to solve your problem more easily.

In Safe Mode:
![Screenshot_20240601_101208](https://github.com/pyoncord/Bunny/assets/37478187/e76a890b-cc81-44a3-9de0-440a35088207)

Not in Safe Mode:
![Screenshot_20240601_101140](https://github.com/pyoncord/Bunny/assets/37478187/6437421a-69f4-49ff-9d1b-a0605dc12318)

**Comment by amsryq** [comment]
Do you have any themes applied? Could be the culprit

**Comment by ViVi-Vibes** [comment]
> Do you have any themes applied? Could be the culprit

If you are asking for stock app themes it's simple dark mode for testing i tried every other theme didn't help. For the pyoncord theme I am using [Catppuccin Mocha](https://raw.githubusercontent.com/catppuccin/vendetta/main/mocha.json). Either way i tried with turning safe mode on it doesn't help. I tried turning off the module via lsposed and the overlay is visible again.

**Comment by amsryq** [comment]
Don't use Bunny's theme, see if that still occurs

**Comment by ViVi-Vibes** [comment]
I forgot to mention i tried it without bunny themes and with default discord themes too didn't help.

**Comment by amsryq** [comment]
Can't reproduce, please make sure you completely killed the app after disapplying your theme and fonts
