### ISSUE TITLE
Bunny Development Discord Server

### ISSUE THREAD

**Issue by tiwna16** [pyoncord/Bunny#5]
Please make a discord server for users where we can discuss about your Bunny or Pyoncord project.It will help us to share our common issues,connect with the developers,help in development,know current ETA on your project & share our thoughts around that.
**The Current shared Pyoncord discord server link expired**.
Users are gonna use github as to share their common problems which can be a mess to tackle around here.
It's a suggestion with request.
You project is really looking a promising one.Wishing you luck for this one.

**Comment by amsryq** [comment]
Are you sure? [This link](https://discord.com/invite/XjYgWXHb9Q) I linked in README is still up.

![Screenshot_20240225-233955](https://github.com/pyoncord/Bunny/assets/82711525/dd24165a-8740-4776-a149-592e2f94ce99)
![Screenshot_20240225-234008](https://github.com/pyoncord/Bunny/assets/82711525/cafece7f-b871-4e79-a5a4-4475df28c246)

**Comment by tiwna16** [comment]
Ahh!
Now I can.Got it.
Was showing link expired in README section of Bunny.
Now It's working.Thanks a lot.
