### ISSUE TITLE
bug: Background image not loaded until theme is reselected

### ISSUE THREAD

**Issue by pterror** [pyoncord/Bunny#53]
not OP of this message, but it's the same issue:
https://discord.com/channels/1196075698301968455/1210652540757090315/1225091476938031114

> image backgrounds on themes are a bit broken on bunny.
>
> If I restart discord the background disappears but changing (or deselecting) theme and back caused the background to show like normal

**Comment by pterror** [comment]
maybe `patchChatBackground` is running before `initThemes` finishes?
maybe
```
updateThemes().then(
  patchChatBackground,
  e => console.error("Failed to update themes", e)
);
```
might work... or making `initThemes` async and `await`ing it:
```
return updateThemes().catch(e => console.error("Failed to update themes", e));
```

(i have no idea how this thing works though so i may be on the wrong track completely)

**Comment by amsryq** [comment]
can you recheck if this is still an issue?

**Comment by pterror** [comment]
my bad, it is still an issue, i've updated just now just to recheck:
