### ISSUE TITLE
Deleted messages appearing during message loading on some servers

### ISSUE THREAD

**Issue by o800** [pyoncord/Bunny#54]
on a very small number of public servers (so far i have only reproduced it on the official backpack hero server with the message shown below but i remember it happening before somewhere else) a deleted message appears during the time before the messages load. this issue does not occur on vanilla discord. 
![screenshot of referenced message](https://github.com/pyoncord/Bunny/assets/151675302/ae0e1c10-1951-4aee-b140-2033614f0441)

additionally, based on the time the message was sent, my client probably shouldn't even know this message ever existed, as i was not online and didn't even have a stable connection at that time.

this also persists across app restarts, and even appears in the actual messages of the active channel for a second upon app startup.

overall this issue is very strange and i wouldn't be surprised if this isn't reproducible

something similar and possibly related that i noticed, is occasionally when loading a channel the first message will load a couple of seconds before the rest, appearing in the same way.

the issue also occurs in safe mode 

android version: 14 discord version: 232.15 bunny version: e9d80c7-main

**Comment by LDzik** [comment]
It is pure accident that's it is NSFW ad. From my experience when channel loads there is one message displayed and for some unknown reason it is usually deleted messages, that's why it is an ad, it was probably deleted and for some reason it is displayed. I had the same "issue" with steam scam.

**Comment by o800** [comment]
Ok makes sense
