### ISSUE TITLE
Bunny stopped working after a ROM update (YAAP)

### ISSUE THREAD

**Issue by github-gitlab** [pyoncord/Bunny#55]
I use a custom ROM called YAAP. Device is OnePlus 7 Pro running Android 14 QPR2.

Bunny does not load after the latest ROM update and is stuck on initial screen and then crashes after a while. The ROM dev thinks upstream ART commits from AOSP 14 might be responsible.

I'm attaching the [repo](https://github.com/yaap/art/commits/fourteen/) for the ART commits, please let me know if any of the commits from June 4 could break Bunny. Other Discord mods like Aliucord, and apparently even xposed/lsposed modules are broken with the new ROM update for what it's worth, not that I use them myself.

ART Repo: https://github.com/yaap/art/commits/fourteen/

I tried reinstalling if it would fix the issue. I am able to install Bunny with the manager but after that the app simply doesn't load and crashes.

I can provide logs if required.

**Comment by dswapnil104** [comment]
Tracking here: https://github.com/mywalkb/LSPosed_mod/issues/113

**Comment by dswapnil104** [comment]
## EDIT
Issue appears to fixed with latest ROM update.
Module injects as expected (with new update, dated) : `YAAP-14-Urshanabi-guacamoleb-20240617`

**Comment by github-gitlab** [comment]
[Aliucord stopped working again](https://github.com/Aliucord/Aliucord/issues/454#issuecomment-2241391728). Looks like the same issue has cropped up with the latest commit added in [this repo](https://github.com/yaap/art/commits/fourteen/)
