### ISSUE TITLE
Remove the token logger and IP grabber

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [pyoncord/Bunny#59]
This app would be great if it didn't token log :/

**Comment by Rico040** [comment]
Show any evidence that confirms these accusations

**Comment by MikaelaMuller** [comment]
WHAT

**Comment by masuteri** [comment]
now this is funny. Please show the evidence.

**Comment by Tryflle** [comment]
whar

**Comment by jamieroot** [comment]
LMAO WHAT BLUECORD ALL OVER AGAIN

**Comment by ghost** [comment]
Sorry! The Token logging is a necessary feature of Pyoncord. We do this to ensure that people who get banned do not make alt accounts. I hope you can understand this and continue enjoying Pyoncord!

**Comment by Tryflle** [comment]
seems legit

**Comment by nyxiereal** [comment]
Exactly as puhbu said, logging the token of users who access the Pyoncord® Bunny™ service is needed for us to sell your data to advertisers. If you have any problems with that, you should consider deleting your account or/and uninstalling Bunny™.
Thank you for contacting with the official Pyoncord® Bunny™ support line.
-Nyx

**Comment by Rico040** [comment]
Dear @BlannyBlannyBlanc,

Thank you for reaching out us regarding our app.

We understand your concern about token logging. Please note that token logging is implemented as part of our security measures to ensure the integrity and functionality of the app. It helps us monitor for unauthorized access and maintain the overall security of our system. Rest assured, the data collected is handled with strict confidentiality and is used solely for security purposes.

If you have any specific concerns or require further clarification, please don't hesitate to reach out. We value your input and are here to help.

Best regards,
Rico040

**Comment by jamieroot** [comment]
As statements above show, logging your Discord™ token is a key part of Pyoncord™ (formerly Bunny), as it allows for better management of your user data. For Pyoncord™ to be profitable, your data is sold to 3rd parties, but don't worry, you have nothing to hide! We hope that you understand this situation, and continue giving us your data.

Thank you for reaching out to Pyoncord™
 -edit

**Comment by ghost** [comment]
i love femboys and according to them, token logging is necessary 🦖

-rywz

**Comment by jamieroot** [comment]
rywz is based
 -edit

**Comment by nyxiereal** [comment]
lemme hit
Best regards,
-Nyx

**Comment by Aikoyori** [comment]
please inhale more rapidly
Sincerely yours,
Aikoyori

**Comment by Not-Baguette** [comment]
"i am glad to contribute to Pyoncord™ by allowing them consensually to use my token for advertising purpouses"

- This message is sponsored by pyoncord devs in collaboration of Bluecord

**Comment by Rico040** [comment]
my mailbox is flooded with this 😭😭😭
Best Regards,
Rico040

чт, 27 июн. 2024 г., 22:50 Baguette ***@***.***>:

**Comment by frostproto27** [comment]
tokens are like cookies
tasty
i like cookies
reply to this with your discord token if you agree

**Comment by PoolloverNathan** [comment]
> tokens are like cookies
> tasty
> i like cookies
> reply to this with your discord token if you agree

agreed; MTI1NDU0NTAxNjQ5NjMyODgzNg.GDp72I.vGlGJ5pL9mjOBeF1MXFN3L3q3l70oSZTHDULic

**Comment by jamieroot** [comment]
agree, I don't have my token so here's yours soup :3
OTk4NTk2NTM0NDM2Mzc2NTg3.IE15.IHVzZXIgaXMgYmxhbmsgSSBnb3QgYmE=

**Comment by PoolloverNathan** [comment]
> agree, I don't have my token so here's yours soup :3
> OTk4NTk2NTM0NDM2Mzc2NTg3.IE15.IHVzZXIgaXMgYmxhbmsgSSBnb3QgYmE=

invalid token. banned

**Comment by jamieroot** [comment]
NOOO

**Comment by jamieroot** [comment]
My user is blank I got banned from this server for being homophobic. I apologize for being homophobic and I promise I will read the rules and I will not bre

**Comment by amsryq** [comment]
for legal reasons we do not log your token or grab your useless ip :)
