### ISSUE TITLE
Big empty space when a message is sent

### ISSUE THREAD

**Issue by I-794** [pyoncord/Bunny#60]
Sometimes when i send a message, A big empty space will appear as if its an emoji but nothing is there.
 ![image](https://github.com/pyoncord/Bunny/assets/147570875/22d12a02-fdc2-4a04-a672-d0fb43a83649)

**Comment by amsryq** [comment]
make sure that this also happens in safe mode AND doesn't happen on vanilla builds

**Comment by I-794** [comment]
> make sure that this also happens in safe mode AND doesn't happen on vanilla builds

![image](https://github.com/user-attachments/assets/78d44c26-cc97-4347-a1e6-50786c9d332f)

On safe mode
