### ISSUE TITLE
There's Vendetta tab on Bunny on both manager and xposed when disabling tabs v2

### ISSUE THREAD

**Issue by ghost** [pyoncord/Bunny#64]
![image](https://github.com/pyoncord/Bunny/assets/82843871/48545567-4fc6-405c-881d-b04ecdbd5af7)

OS: Chrome OS 126

**Comment by amsryq** [comment]
known issue. fixing it isn't as simple, considering the old UI is almost obsolete I chose to ignore it... PRs are welcome
