### ISSUE TITLE
DM menu is completely blank even in safemode.

### ISSUE THREAD

**Issue by PikachuGabe** [pyoncord/Bunny#65]
![Screenshot_20240711_201635](https://github.com/user-attachments/assets/268150a2-60ad-4994-901d-b751d34864d3)
![Screenshot_20240711_201621](https://github.com/user-attachments/assets/f31f8adc-5753-4bb8-8af0-9cc6db253208)
![Screenshot_20240711_195723](https://github.com/user-attachments/assets/94650c26-ea25-4448-ac5d-af9112e5cb01)
![Screenshot_20240711_195842](https://github.com/user-attachments/assets/cc491e17-6d25-4645-bf64-df7ae7cf1672)
All relevant info, that being an example of the dysfunctional DM ui, enabled experiments and client info. Pyoncord is in safemode in these images.

**Comment by PalmDevs** [comment]
Discord made the messages tab UI not render a bit ago. There's no way you can get it back unless you use an older version (< 237).
