### ISSUE TITLE
When using Sapphire big empty spot when using a button

### ISSUE THREAD

**Issue by I-794** [pyoncord/Bunny#66]
https://github.com/user-attachments/assets/0f04e70d-6340-44a6-80d0-4ad8c971fc67

**Comment by Rico040** [comment]
plugin issue

**Comment by I-794** [comment]
> plugin issue

Which one?

**Comment by Rico040** [comment]
MessageLogger or NoDelete, one of these

чт, 18 июл. 2024 г., 09:37 Charlie ***@***.***>:
