### ISSUE TITLE
bug: Bunny crashes on Android 15 Beta 4

### ISSUE THREAD

**Issue by JetyWawoo** [pyoncord/Bunny#67]
Steps to reproduce:
1. Update to Android 15 Beta 4
2. Launch Bunny (Stable, Beta, Alpha) (Non-root)
3. It closes instantly, get owned

**Comment by Rico040** [comment]
LSPosed supports up to A15 Beta 2

**Comment by ponpat** [comment]
I can confirm, beta 3 worked still fine. Issue only arised after beta 4 update. I'm not sure what changed in between. I checked all other apps and they all work properly. 

If it's LSPosed related and it only support up to beta 2, shouldn't the issues have started on 3 already?

**Comment by NeytirX** [comment]
Issue started on beta 4 on my end, however, I had to update my bunny in beta 3

**Comment by imide** [comment]
Issue occuring for me on b5, never happened on B4 or 3.

**Comment by GayPotatoEmma** [comment]
> Issue occuring for me on b5, never happened on B4 or 3.

You may be mixing up Beta 3.1 with Beta 4. There is no Beta 5 nor is there one planned.

That being said, can also confirm it's crashing on Pixel 8 Pro on 15b4

**Comment by imide** [comment]
> You may be mixing up Beta 3.1 with Beta 4. There is no Beta 5 nor is there one planned.

oops! mb, thanks for the correction

**Comment by theoparis** [comment]
I got more information from `adb logcat --buffer=crash` 🤔 
```
07-25 13:46:50.670 31903 31903 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.discord.MainApplication" on path: DexPathList[[zip file "/data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/base.apk", zip file "/data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.arm64_v8a.apk", zip file "/data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.en.apk", zip file "/data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/lib/arm64, /data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/base.apk!/lib/arm64-v8a, /data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~fEZohDZdFYS6sdneYUFxsA==/io.github.pyoncord.app-ow-LA50Z08b0TfD_kOwJ9A==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
```

**Comment by ballo** [comment]
This is also happening to me. 
Baseband version g5300q-240704-240707-B-12055926,g5300q-240704-240707-B-12055926
Kernel version 5.10.209-android13-4-00008-g28a6e1ad779c-ab11971276
#1 Fri Jun 14 01:29:26 UTC 2024

**Comment by Shuflduf** [comment]
Installing with Shizuku doesn't fix this

**Comment by Rico040** [comment]
duh

**Comment by Shuflduf** [comment]
:(

**Comment by theoparis** [comment]
> :(

The mentioned pr fixes the issue, you can [download the debug apk from GitHub Actions for the time being](https://github.com/pyoncord/BunnyManager/actions/runs/10107978853?pr=20). I had to remove the existing apps beforehand in order to fully reinstalll Bunny.

**Comment by amsryq** [comment]
https://github.com/pyoncord/BunnyManager/releases/tag/1006 should do

**Comment by ballo** [comment]
I was prompted for an update but it still crashes on launch

Edit: OK I had to install the new manager first and it works. The old manager prompted me to update but that didn't work.
