### ISSUE TITLE
Feature request: Un-restrict Discord's text selection context menu

### ISSUE THREAD

**Issue by Raffael7777** [pyoncord/Bunny#68]
By default the Android Discord app restricts the text selection context menu options within the message input box. On my device, the only options shown are Cut, Copy, Paste, Share, Select All, and Read Aloud. Other Android apps might add useful features as Android context menu options. For example, [TextTools](https://github.com/corphish/TextTools) could be used to surround selected text with markdown formatting, or a translation app (there are several with a context option for this) being able to automatically translate the selected text, enabling foreign language speakers the ability to type in their native language and translate it without having to swap between apps or copy and paste. But Discord doesn't allow users the freedom to use those options. I doubt a Bunny/Vendetta plugin would be able to change/expand/unrestrict the available text selection context menu options to all which are available on a user's Android device, because this is most likely set by the app itself, but it might be possible for Bunny to do so. If is possible, I think this feature would enable users to use their phone and apps in the way users want to, instead of having their available features limited by Discord Inc.

**Comment by amsryq** [comment]
Although this is theoretically possible to be implemented by Bunny (through Xposed module), this is still isn't within Bunny scope and ideally should be a plugin, hence just another "not possible" plugin idea. We might allow it at some point in the future, but not in the mean time
