### ISSUE TITLE
bug: Unable to open/select files

### ISSUE THREAD

**Issue by Freminet** [pyoncord/Bunny#69]
**Describe the bug**
Bunny doesn't let you select specific files to upload them to Discord. Simply put, you cannot "select" any file and open it.

**To Reproduce**
1. Go to any channel
2. Click the "+" button to send files
3. Click once again the "Files" button
4. Try to select any file and then open it, you can't.

**Expected behavior**
It should just open the file and upload it to Discord

**Device Information (please complete the following information):**
 - Device: IP15PM
 - OS: iOS 17.5.1
 - Discord Version: (App Version 236.0, JS build number 60807)
 - Bunny Version: e9d80c7-main

**Checklists**
- [X] I understand that this is a bug report and not a place to request new features or plugins
- [X] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

Sorry if this has been addressed before, but I couldn't find anything on it.

**Comment by Rico040** [comment]
not a bug of bunny itself but rather limitation of sideloaded app

**Comment by Freminet** [comment]
> not a bug of bunny itself but rather limitation of sideloaded app

Oh I see, that's sad cause it really makes uploading files now harder.
