### ISSUE TITLE
Bunny iOS Tweak - I made my own

### ISSUE THREAD

**Issue by mucookul** [pyoncord/Bunny#7]
Mostly just a fork of VendettaTweak with some tiny things changed like naming the loader as BunnyTweak in discord settings, and setting xposed to use Bunny's

https://github.com/Mukul1127/BunnyUnofficialTweak

**Comment by amsryq** [comment]
Would you be able to contact me on Discord so we can discuss this further? - `pylixonly`

**Comment by mucookul** [comment]
I sent a dm
