### ISSUE TITLE
bug: side menu doesn't work very well 

### ISSUE THREAD

**Issue by RemagOfficial** [pyoncord/Bunny#75]
**Describe the bug**
the side menu in chats that shows the member count and media and such doesn't let you jump to the messages that it shows, my plugins seem to make it worse but there's still issues in safe mode that don't exist in vanilla discord

**To Reproduce**
1. Go to any chat, DM or server channel 
2. swipe to show the member list
3. switch to for example pins and try and go to the pinned message

**Expected behavior**
when you click on a pinned message it should take you to the message in the chat, same for clicking the "jump to message" button for media

**Device Information (please complete the following information):**
 - Device: Samsung S20 FE 5G
 - OS: android 13
 - Discord Version: 243016
 - Bunny Version: 22925c0-main

**Checklists**
- [x] I understand that this is a bug report and not a place to request new features or plugins
- [x] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by Rico040** [comment]
not bunny's issue, since you're using experiment feature of discord

**Comment by RemagOfficial** [comment]
it works completely fine on vanilla discord and I don't think the member list is an experimental option

**Comment by amsryq** [comment]
> I don't think the member list is an experimental option

swipe to view member list is an experiment

**Comment by RemagOfficial** [comment]
swiping isn't the issue, it happens when you view the member list regardless of how

**Comment by amsryq** [comment]
try again with the experiment off and see if that still persists
