### ISSUE TITLE
bug: uh

### ISSUE THREAD

**Issue by Duder-driod** [pyoncord/Bunny#76]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Discord Version [e.g. 222111]
 - Bunny Version [e.g e19e89c-main]

**Checklists**
- [ ] I understand that this is a bug report and not a place to request new features or plugins
- [ ] I understand that this is no place to report bugs produced by a plugin
- [ ] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by danilwhale** [comment]
okay

**Comment by nyxiereal** [comment]
vro whar the devils

**Comment by ghost** [comment]
I want to extend my sincere appreciation to you for opening the GitHub issue and providing such a thorough and clear explanation. Your detailed account of the problem and your methodical approach to outlining the steps to reproduce it are incredibly valuable. Your effort not only helps in addressing the issue more efficiently but also enhances the overall quality of the project by ensuring that we understand the problem from every angle. Thank you for taking the time to contribute in such a constructive manner; it truly makes a difference in the development process. We’ll address and fix that bug as soon as possible.

**Comment by jirmu** [comment]
USHIE FİX THE BUG
