### ISSUE TITLE
Bunny won't work

### ISSUE THREAD

**Issue by ghost** [pyoncord/Bunny#86]
Hello devs, 
I just updated pyoncord to 246.22 and it constantly crashes when I try to run it.
I'm running Android 13 on a Xiaomi Redmi.
I'm sorry if this is alrdy known, I just checked ur server and I haven't found any announcements related to the issue.

**Comment by aaronjamt** [comment]
Also having the same issue, any updates? Sometimes it'll load when clicking on notifications, but even that isn't consistent. I checked logcat and couldn't find anything super obvious at a quick glance, except that there's some manifest file it's trying to load from Discord's server, then nothing else until I close the app.

**Comment by amsryq** [comment]
try again with latest version and file a proper bug report with the bug report issue template
