### ISSUE TITLE
bug:  cant type anything in plugins and themes 

### ISSUE THREAD

**Issue by noreston** [pyoncord/Bunny#87]
when i open up the "plugins" button and try importing a plugin it tells me to type in a link but theres nowhere to put the link into
![IMG_9326](https://github.com/user-attachments/assets/6381a2ed-d94e-4598-89ee-5c48839b4c73)
![IMG_9328](https://github.com/user-attachments/assets/5932c486-a927-4a89-8b63-c3ed43e85b89)

**Comment by mudrhiod** [comment]
I think the fix you did (the one mentioned on [mareks PR](https://github.com/pyoncord/Bunny/pull/91)) causes a crash when clicking add plugin/themes button
![Screenshot_2024-10-11-13-07-04-84_02eefeb97de4987ad7a651debf04eb01](https://github.com/user-attachments/assets/5ff1f0b8-1856-4eec-8523-b480f7515bf8)

**Comment by AwertaDreams** [comment]
Same here, can't type anything. Im on 224.19
