### ISSUE TITLE
bug: Infinite loading screen v1.0.6

### ISSUE THREAD

**Issue by ghost** [pyoncord/Bunny#92]
The loading screen in the Pyoncord Discord mod never stops, preventing access to the app's features. The user interface remains stuck on the "Bezig met laden (loading in English)" message indefinitely.

**Device Details:**
- Device: Samsung Galaxy A54 5G
- OS: Android 14
- App Version: v1.0.6

**Additional Information:**
- The issue persists after restarting the app.
- No error messages are displayed.

**Attachments:**
- Screenshot of the loading screen
![Screenshot_20241012_215929_Bunny Manager](https://github.com/user-attachments/assets/2c6b7664-ff94-429e-a80e-cd94fd120b6b)

**Comment by Maganoos** [comment]
Having the same issue on both Samsung Galaxy s21 and s9

**Comment by ghost** [comment]
> Having the same issue on both Samsung Galaxy s21 and s9

Did you find a fix?

**Comment by amsryq** [comment]
Network issue, try a different ISP/network or use a VPN and perform a restart
