### ISSUE TITLE
bug: Stuck at discord logo screen

### ISSUE THREAD

**Issue by Baldi89989** [pyoncord/Bunny#93]
**Describe the bug**
I’m stuck at discord logo screen after bunny has crashed and clicked "Reload discord"

**To Reproduce**

**Device Information (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18.0.1
 - Discord Version 250.0
 - Bunny Version 247.0

**Checklists**
- [x] I understand that this is a bug report and not a place to request new features or plugins
- [x] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by unatried** [comment]
Tried reinstalling?

**Comment by Baldi89989** [comment]
Will i lose my plugins if i reinstall?

**Comment by aaronjamt** [comment]
> Will i lose my plugins if i reinstall?

Yes, although I just reinstalled the app, and it seems to be working now. I wonder if it's an issue with a plugin, maybe

**Comment by amsryq** [comment]
not detailed enough
