### ISSUE TITLE
bug: Patched Discord may end up not loading Discord at all

### ISSUE THREAD

**Issue by Bronya-Rand** [pyoncord/Bunny#95]
**Describe the bug**
For the last week or two, I faced a bit of a problem regarding my Bunny patched Discord in which it would just hang at the Discord logo once launched and never really transition to my messages or last talked server. This is rather weird given I been using Bunny for a while and it seems to only affect the app as of now.

The funny thing is that I use Bunny also in a Secure Folder instance on my phone to swap to different Discord accounts and that works fine (same version number and build as they are mirrored basically).

Seems like the only fix is to clear all your data and resign in but I will say it happened around 1-2 weeks ago in the case where a past commit might have broke something or just the Discord I downloaded was borked in some way (I mainly build under Discord Alpha). The normal Discord app (which is also Alpha) with the same version number works fine.

**To Reproduce**
1. Use Bunny for a relative period of time with updates every now and then.
2. Launch Bunny Patched Discord
3. Discord hangs at the Discord icon screen.

**Expected behavior**
Discord should load into direct messages or friend list or last channel I interacted in.

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy S24 Ultra
 - OS: Android 14
 - Discord Version 253.7 Alpha
 - Bunny Version: Unknown

I did not use any plugins whatsoever.

**Checklists**
- [x] I understand that this is a bug report and not a place to request new features or plugins
- [x] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by trustytrojan** [comment]
fyi bunny has discontinued development, check their discord for more info. for a more up-to-date vendetta fork check out [revenge](https://github.com/revenge-mod). i don't have the issue you described on here, though i don't use secure folder
