### ISSUE TITLE
change: Error boundary colours

### ISSUE THREAD

**Issue by mudrhiod** [pyoncord/Bunny#96]
**Describe the change**
It's for the new crash screen merged from dev

The outer background is `BACKGROUND_PRIMARY`
The inner background is `BG_BASE_PRIMARY`

I am requesting for the outer background to be changed to `BG_BASE_SECONDARY` and inner background to `CARD_PRIMARY_BG`

`BG_BASE_SECONDARY` - outer background for settings pages
`CARD_PRIMARY_BG` - plugin/theme cards
This change is a very small and probably dumb one but for the sake of consistency and theming purposes it would genuinely help.

**Comment by amsryq** [comment]
> The outer background is `BACKGROUND_PRIMARY`

Use of `BACKGROUND_PRIMARY` is retained from Vendetta:
https://github.com/vendetta-mod/Vendetta/blob/rewrite/src/ui/safeMode.tsx#L18-L22
How could the change affect the consistency? Is this something recently affected or it has been a while? And why should it be `BG_BASE_SECONDARY`?

> `CARD_PRIMARY_BG` - plugin/theme cards

The colors of these cards are decided by Discord itself, I'm can't see how it could be inconsistent and trying to change this color would be hacky somewhat. Do they differ from Discord's use?

**Comment by mudrhiod** [comment]
> > The outer background is `BACKGROUND_PRIMARY`
> 
> Use of `BACKGROUND_PRIMARY` is retained from Vendetta: https://github.com/vendetta-mod/Vendetta/blob/rewrite/src/ui/safeMode.tsx#L18-L22 How could the change affect the consistency? Is this something recently affected or it has been a while? And why should it be `BG_BASE_SECONDARY`?
> 
BG_BASE_SECONDARY is used across settings pages, members list, profiles and even bunny's own pages. It would be more consistent in that case

<details>
<summary>Examples</summary>
<img src="https://github.com/user-attachments/assets/9b3fa77d-f975-407f-9a32-d8e38b00b874" width="500">
<img src="https://github.com/user-attachments/assets/e64bc921-2303-4e95-8fc2-5e57d3fdc33f" width="500">
<img src="https://github.com/user-attachments/assets/b515a079-9bbe-43b4-a134-6b330443e6f7" width="500">
</details>

As far as I'm aware the only things that still uses background_primary are is the search page and "jump to message"


> > `CARD_PRIMARY_BG` - plugin/theme cards
> 
> The colors of these cards are decided by Discord itself, I'm can't see how it could be inconsistent and trying to change this color would be hacky somewhat. Do they differ from Discord's use?

Not sure what you mean by this (sorry)

**Comment by mudrhiod** [comment]
Also there are themes, such as catppuccin, which follow strict colour pallets and getting around the backgrounds being the same colour seems impossible to me lol. Catppuccin isn't the only theme like this probably

**Comment by amsryq** [comment]
> Not sure what you mean by this (sorry)

`Card` is not our own component, rather Discord's. We don't define its colors.

**Comment by mudrhiod** [comment]
Oh right. Well either way themers can still change the colour of `CARD_PRIMARY_BG`. Just like the other string it's used by discord in many places and even on bunny's own pages
<details>
<summary>Examples</summary>
<img src="https://github.com/user-attachments/assets/c5f84c47-15f2-4b91-92d1-8852f0397b01" width="500">
<img src="https://github.com/user-attachments/assets/01325f0d-3509-4653-b361-e9064824844d" width="500">
<img src="https://github.com/user-attachments/assets/61f05422-2307-4509-8b06-50774463c9be" width="500">
</details>
