### ISSUE TITLE
bug: Bunny freezes on 254218

### ISSUE THREAD

**Issue by PalmDevs** [pyoncord/Bunny#99]
**Describe the bug**
The app freezes on the Discord logo on 254218.

**To Reproduce**
1. Install Bunny using Bunny Manager while making sure it is installing 254218 build of Discord
2. Launch the app

**Expected behavior**
The app does not freeze and works correctly.

**Screenshots**
(none provided, it should be clear enough what is happening)

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: Android 14
 - Discord Version: 254218
 - Bunny Version: a0d467a-main

**Checklists**
- [x] I understand that this is a bug report and not a place to request new features or plugins
- [x] I understand that this is no place to report bugs produced by a plugin
- [x] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Additional information**

Discord has renamed:
- `ClientInfoManager` -> `NativeClientInfoModule`
- `RTNFileManager` -> `NativeFileModule`
- `RTNDeviceManager` -> `NativeDeviceModule`
- `RTNThemeManager` -> `NativeThemeModule`

in this build. <sub>I am predicting that this will happen more in the future.</sub>

However, Bunny requires some more fixes to work and I currently have no leads. This is one step to it.

**Comment by irresistibl** [comment]
> **Describe the bug** The app freezes on the Discord logo on 254218.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install Bunny using Bunny Manager while making sure it is installing 254218 build of Discord
> 
>     2. Launch the app
> 
> 
> **Expected behavior** The app does not freeze and works correctly.
> 
> **Screenshots** (none provided, it should be clear enough what is happening)
> 
> **Device Information (please complete the following information):**
> 
>     * Device: Samsung Galaxy A13
> 
>     * OS: Android 14
> 
>     * Discord Version: 254218
> 
>     * Bunny Version: [a0d467a](https://github.com/bunny-mod/Bunny/commit/a0d467a3468b3076a74eed983cc0bf380d63a5fc)-main
> 
> 
> **Checklists**
> 
>     * [x]  I understand that this is a bug report and not a place to request new features or plugins
> 
>     * [x]  I understand that this is no place to report bugs produced by a plugin
> 
>     * [x]  I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord
> 
> 
> **Additional information**
> 
> Discord has renamed:
> 
>     * `ClientInfoManager` -> `NativeClientInfoModule`
> 
>     * `RTNFileManager` -> `NativeFileModule`
> 
>     * `RTNDeviceManager` -> `NativeDeviceModule`
> 
>     * `RTNThemeManager` -> `NativeThemeModule`
> 
> 
> in this build. I am predicting that this will happen more in the future.
> 
> However, Bunny requires some more fixes to work and I currently have no leads. This is one step to it.

I can confirm that I'm also experiencing this issue.

Device Information (please complete the following information):

Device: Samsung Galaxy Note20 Ultra 5G
OS: Android 13
Bunny Version: [a0d467a](https://github.com/bunny-mod/Bunny/commit/a0d467a3468b3076a74eed983cc0bf380d63a5fc)

**Comment by meadf1** [comment]
it is happening in ios too, my fix was disabling my current theme, it can work on android too, but I am not sure. ![image](https://github.com/user-attachments/assets/5c3da365-f6e2-4fb5-b0f4-f8b782758c07)
to disable the theme I went to bunny files and deleted current-theme.json from pyoncord folder. I am not sure if this file is the same in android, I will test it latet!

**Comment by Rob07erto** [comment]
Doesn't work :(
